# -*- coding: utf-8 -*-
"""Neue Eintraege fuer bisher unbesetzte Themen.

Zahlen, Pronomen, Hoeflichkeits- und Fragepartikeln, Fragewoerter, Grundverben,
fehlende Monate, Klassifikatoren, Grundnahrungsmittel, Tiere, Koerperteile und
Alltagsfloskeln fehlten im Bestand vollstaendig.
"""

# (thai, rtgs, pos, gloss_de, topic, example_th, example_de)
NEW_WORDS = [
    # --- Zahlen ---
    ("ศูนย์", "sun", "Numerale", "null", "Zahlen",
     "ตอนนี้อุณหภูมิศูนย์องศา", "Die Temperatur ist jetzt null Grad."),
    ("หนึ่ง", "nueng", "Numerale", "eins", "Zahlen",
     "ขอกาแฟหนึ่งแก้ว", "Einen Kaffee, bitte."),
    ("สอง", "song", "Numerale", "zwei", "Zahlen",
     "ฉันมีพี่สาวสองคน", "Ich habe zwei aeltere Schwestern."),
    ("สาม", "sam", "Numerale", "drei", "Zahlen",
     "เขารอสามชั่วโมง", "Er hat drei Stunden gewartet."),
    ("สี่", "si", "Numerale", "vier", "Zahlen",
     "โต๊ะนี้มีสี่ที่นั่ง", "Dieser Tisch hat vier Plaetze."),
    ("ห้า", "ha", "Numerale", "fuenf", "Zahlen",
     "รถไฟออกห้าโมงเย็น", "Der Zug faehrt um fuenf Uhr nachmittags."),
    ("หก", "hok", "Numerale", "sechs", "Zahlen",
     "ฉันตื่นหกโมงเช้าทุกวัน", "Ich stehe jeden Tag um sechs Uhr auf."),
    ("เจ็ด", "chet", "Numerale", "sieben", "Zahlen",
     "หนึ่งสัปดาห์มีเจ็ดวัน", "Eine Woche hat sieben Tage."),
    ("แปด", "paet", "Numerale", "acht", "Zahlen",
     "เขาทำงานวันละแปดชั่วโมง", "Er arbeitet acht Stunden am Tag."),
    ("เก้า", "kao", "Numerale", "neun", "Zahlen",
     "ร้านเปิดเก้าโมงเช้า", "Der Laden oeffnet um neun Uhr."),
    ("สิบ", "sip", "Numerale", "zehn", "Zahlen",
     "ขอเวลาสิบนาที", "Gib mir zehn Minuten."),
    ("ร้อย", "roi", "Numerale", "hundert", "Zahlen",
     "เสื้อตัวนี้ราคาสามร้อยบาท", "Dieses Hemd kostet dreihundert Baht."),
    ("พัน", "phan", "Numerale", "tausend", "Zahlen",
     "ค่าห้องคืนละหนึ่งพันบาท", "Das Zimmer kostet tausend Baht pro Nacht."),

    # --- Pronomen ---
    ("ผม", "phom", "Pronomen", "ich (maennlich)", "Pronomen",
     "ผมมาจากเยอรมนี", "Ich komme aus Deutschland."),
    ("ฉัน", "chan", "Pronomen", "ich (weiblich; informell)", "Pronomen",
     "ฉันชอบอาหารไทย", "Ich mag thailaendisches Essen."),
    ("คุณ", "khun", "Pronomen", "du; Sie", "Pronomen",
     "คุณพูดภาษาไทยได้ไหม", "Sprechen Sie Thai?"),
    ("เขา", "khao", "Pronomen", "er; sie", "Pronomen",
     "เขาเป็นเพื่อนของฉัน", "Er ist mein Freund."),
    ("เธอ", "thoe", "Pronomen", "sie; du (vertraut)", "Pronomen",
     "เธอทำงานที่โรงพยาบาล", "Sie arbeitet im Krankenhaus."),
    ("เรา", "rao", "Pronomen", "wir", "Pronomen",
     "เราไปตลาดด้วยกัน", "Wir gehen zusammen zum Markt."),
    ("มัน", "man", "Pronomen", "es", "Pronomen",
     "มันอร่อยมาก", "Es ist sehr lecker."),

    # --- Partikeln ---
    ("ครับ", "khrap", "Partikel", "hoefliche Schlusspartikel (Mann)", "Grammatik & Partikeln",
     "สวัสดีครับ", "Guten Tag. (von einem Mann gesprochen)"),
    ("ค่ะ", "kha", "Partikel", "hoefliche Schlusspartikel (Frau, Aussage)", "Grammatik & Partikeln",
     "ขอบคุณค่ะ", "Danke. (von einer Frau gesprochen)"),
    ("นะ", "na", "Partikel", "abschwaechende Partikel; ja?", "Grammatik & Partikeln",
     "ไปกันนะ", "Lass uns gehen, ja?"),
    ("ไหม", "mai", "Partikel", "Fragepartikel (ja/nein)", "Grammatik & Partikeln",
     "คุณหิวไหม", "Hast du Hunger?"),
    ("หรือ", "rue", "Konjunktion/Partikel", "oder; Fragepartikel", "Grammatik & Partikeln",
     "ชาหรือกาแฟ", "Tee oder Kaffee?"),
    ("แล้ว", "laeo", "Partikel/Adverb", "schon; bereits", "Grammatik & Partikeln",
     "ฉันกินข้าวแล้ว", "Ich habe schon gegessen."),
    ("ยัง", "yang", "Adverb", "noch; noch nicht", "Grammatik & Partikeln",
     "เขายังไม่มา", "Er ist noch nicht gekommen."),
    ("จะ", "cha", "Partikel", "werden (Zukunft)", "Grammatik & Partikeln",
     "พรุ่งนี้ฉันจะไปเชียงใหม่", "Morgen fahre ich nach Chiang Mai."),

    # --- Fragewoerter ---
    ("อะไร", "arai", "Fragewort", "was", "Fragewoerter",
     "นี่คืออะไร", "Was ist das?"),
    ("ใคร", "khrai", "Fragewort", "wer", "Fragewoerter",
     "ใครอยู่ที่บ้าน", "Wer ist zu Hause?"),
    ("ที่ไหน", "thi nai", "Fragewort", "wo", "Fragewoerter",
     "ห้องน้ำอยู่ที่ไหน", "Wo ist die Toilette?"),
    ("เมื่อไหร่", "muea rai", "Fragewort", "wann", "Fragewoerter",
     "คุณจะกลับเมื่อไหร่", "Wann kommst du zurueck?"),
    ("ทำไม", "tham mai", "Fragewort", "warum", "Fragewoerter",
     "ทำไมคุณมาสาย", "Warum kommst du zu spaet?"),
    ("อย่างไร", "yang rai", "Fragewort", "wie", "Fragewoerter",
     "ไปสถานีรถไฟอย่างไร", "Wie komme ich zum Bahnhof?"),
    ("เท่าไหร่", "thao rai", "Fragewort", "wie viel", "Fragewoerter",
     "อันนี้ราคาเท่าไหร่", "Wie viel kostet das?"),

    # --- Grundverben ---
    ("เป็น", "pen", "Verb", "sein (Zustand, Beruf)", "Alltagsverben",
     "เขาเป็นครู", "Er ist Lehrer."),
    ("มี", "mi", "Verb", "haben; es gibt", "Alltagsverben",
     "ที่นี่มีร้านกาแฟไหม", "Gibt es hier ein Cafe?"),
    ("อยาก", "yak", "Verb", "moechten; wollen", "Alltagsverben",
     "ฉันอยากไปทะเล", "Ich moechte ans Meer fahren."),
    ("ต้อง", "tong", "Verb", "muessen", "Alltagsverben",
     "ผมต้องทำงานวันนี้", "Ich muss heute arbeiten."),
    ("ได้", "dai", "Verb", "koennen; bekommen", "Alltagsverben",
     "คุณช่วยผมได้ไหม", "Kannst du mir helfen?"),
    ("ช่วย", "chuai", "Verb", "helfen", "Alltagsverben",
     "ช่วยพูดช้าๆ หน่อย", "Sprich bitte etwas langsamer."),
    ("ทำ", "tham", "Verb", "machen; tun", "Alltagsverben",
     "คุณทำอะไรอยู่", "Was machst du gerade?"),
    ("ให้", "hai", "Verb", "geben; lassen", "Alltagsverben",
     "เขาให้หนังสือกับฉัน", "Er hat mir ein Buch gegeben."),
    ("เอา", "ao", "Verb", "nehmen; haben wollen", "Alltagsverben",
     "ผมเอาอันนี้", "Ich nehme das hier."),
    ("พูด", "phut", "Verb", "sprechen", "Alltagsverben",
     "เธอพูดภาษาไทยเก่ง", "Sie spricht gut Thai."),
    ("ดู", "du", "Verb", "sehen; anschauen", "Alltagsverben",
     "เราดูหนังด้วยกัน", "Wir schauen zusammen einen Film."),
    ("ฟัง", "fang", "Verb", "hoeren; zuhoeren", "Alltagsverben",
     "ผมฟังเพลงไทยทุกวัน", "Ich hoere jeden Tag thailaendische Musik."),
    ("นอน", "non", "Verb", "schlafen; liegen", "Alltagsverben",
     "เด็กนอนหลับแล้ว", "Das Kind schlaeft schon."),
    ("รอ", "ro", "Verb", "warten", "Alltagsverben",
     "กรุณารอสักครู่", "Bitte warten Sie einen Moment."),

    # --- fehlende Monate + Woche ---
    ("มกราคม", "makarakhom", "Nomen", "Januar", "Zeit & Kalender",
     "ปีใหม่อยู่ในเดือนมกราคม", "Neujahr ist im Januar."),
    ("กุมภาพันธ์", "kumphaphan", "Nomen", "Februar", "Zeit & Kalender",
     "เดือนกุมภาพันธ์สั้นที่สุด", "Der Februar ist der kuerzeste Monat."),
    ("เมษายน", "mesayon", "Nomen", "April", "Zeit & Kalender",
     "เดือนเมษายนร้อนมากในไทย", "Der April ist in Thailand sehr heiss."),
    ("พฤษภาคม", "phruetsaphakhom", "Nomen", "Mai", "Zeit & Kalender",
     "ฝนเริ่มตกในเดือนพฤษภาคม", "Im Mai faengt der Regen an."),
    ("มิถุนายน", "mithunayon", "Nomen", "Juni", "Zeit & Kalender",
     "เราไปเที่ยวเดือนมิถุนายน", "Wir verreisen im Juni."),
    ("กันยายน", "kanyayon", "Nomen", "September", "Zeit & Kalender",
     "โรงเรียนเปิดเดือนกันยายน", "Die Schule beginnt im September."),
    ("ตุลาคม", "tulakhom", "Nomen", "Oktober", "Zeit & Kalender",
     "อากาศเย็นลงในเดือนตุลาคม", "Im Oktober wird es kuehler."),
    ("สัปดาห์", "sapda", "Nomen", "Woche", "Zeit & Kalender",
     "ผมทำงานห้าวันต่อสัปดาห์", "Ich arbeite fuenf Tage pro Woche."),

    # --- Klassifikatoren ---
    ("อัน", "an", "Klassifikator", "Klassifikator fuer kleine Dinge", "Klassifikatoren",
     "ขออันนี้หนึ่งอัน", "Ich haette gern eins davon."),
    ("ตัว", "tua", "Klassifikator", "Klassifikator fuer Tiere und Kleidung", "Klassifikatoren",
     "เขามีแมวสองตัว", "Er hat zwei Katzen."),
    ("ใบ", "bai", "Klassifikator", "Klassifikator fuer Blaetter und Behaelter", "Klassifikatoren",
     "ฉันซื้อกระเป๋าหนึ่งใบ", "Ich habe eine Tasche gekauft."),
    ("เล่ม", "lem", "Klassifikator", "Klassifikator fuer Buecher", "Klassifikatoren",
     "ผมอ่านหนังสือสามเล่ม", "Ich habe drei Buecher gelesen."),
    ("ขวด", "khuat", "Klassifikator", "Flasche (Klassifikator)", "Klassifikatoren",
     "ขอน้ำหนึ่งขวด", "Eine Flasche Wasser, bitte."),
    ("แก้ว", "kaeo", "Klassifikator", "Glas (Klassifikator)", "Klassifikatoren",
     "เขาดื่มชาสองแก้ว", "Er hat zwei Glas Tee getrunken."),

    # --- Essen ---
    ("ไก่", "kai", "Nomen", "Huhn; Haehnchen", "Essen & Trinken",
     "ฉันสั่งข้าวผัดไก่", "Ich bestelle gebratenen Reis mit Haehnchen."),
    ("หมู", "mu", "Nomen", "Schwein; Schweinefleisch", "Essen & Trinken",
     "หมูย่างอร่อยมาก", "Gegrilltes Schweinefleisch ist sehr lecker."),
    ("ไข่", "khai", "Nomen", "Ei", "Essen & Trinken",
     "ผมกินไข่ทุกเช้า", "Ich esse jeden Morgen ein Ei."),
    ("ผัก", "phak", "Nomen", "Gemuese", "Essen & Trinken",
     "เด็กไม่ชอบกินผัก", "Kinder essen nicht gern Gemuese."),
    ("ผลไม้", "phonlamai", "Nomen", "Obst", "Essen & Trinken",
     "ตลาดมีผลไม้สดทุกวัน", "Auf dem Markt gibt es taeglich frisches Obst."),
    ("ก๋วยเตี๋ยว", "kuaitiao", "Nomen", "Nudelsuppe", "Essen & Trinken",
     "ร้านนี้ขายก๋วยเตี๋ยวอร่อย", "Dieser Laden verkauft leckere Nudelsuppe."),
    ("ต้มยำ", "tom yam", "Nomen", "Tom Yam (scharfe Suppe)", "Essen & Trinken",
     "ต้มยำกุ้งเผ็ดมาก", "Tom Yam Gung ist sehr scharf."),
    ("ส้มตำ", "som tam", "Nomen", "Papayasalat", "Essen & Trinken",
     "ส้มตำเป็นอาหารอีสาน", "Som Tam ist ein Gericht aus dem Isaan."),

    # --- Tiere ---
    ("หมา", "ma", "Nomen", "Hund", "Tiere",
     "หมาของเพื่อนน่ารัก", "Der Hund meines Freundes ist suess."),
    ("นก", "nok", "Nomen", "Vogel", "Tiere",
     "มีนกอยู่บนต้นไม้", "Auf dem Baum sitzt ein Vogel."),
    ("ช้าง", "chang", "Nomen", "Elefant", "Tiere",
     "ช้างเป็นสัตว์ประจำชาติไทย", "Der Elefant ist Thailands Nationaltier."),
    ("งู", "ngu", "Nomen", "Schlange", "Tiere",
     "ระวังงูในสวน", "Vorsicht vor Schlangen im Garten."),
    ("ยุง", "yung", "Nomen", "Muecke", "Tiere",
     "ตอนเย็นมียุงเยอะ", "Am Abend gibt es viele Muecken."),

    # --- Koerper ---
    ("ขา", "kha", "Nomen", "Bein", "Gesundheit & Koerper",
     "ขาของผมเจ็บ", "Mein Bein tut weh."),
    ("แขน", "khaen", "Nomen", "Arm", "Gesundheit & Koerper",
     "เธอยกแขนขึ้น", "Sie hob den Arm."),
    ("ท้อง", "thong", "Nomen", "Bauch", "Gesundheit & Koerper",
     "ฉันปวดท้องตั้งแต่เมื่อวาน", "Ich habe seit gestern Bauchschmerzen."),
    ("หลัง", "lang", "Nomen/Praeposition", "Ruecken; hinter", "Gesundheit & Koerper",
     "ผมปวดหลังตอนเช้า", "Ich habe morgens Rueckenschmerzen."),
    ("นิ้ว", "nio", "Nomen", "Finger; Zoll", "Gesundheit & Koerper",
     "เขาชี้ด้วยนิ้ว", "Er zeigt mit dem Finger."),

    # --- Floskeln ---
    ("ไม่เป็นไร", "mai pen rai", "Phrase", "macht nichts; kein Problem", "Begruessung & Hoeflichkeit",
     "ไม่เป็นไรครับ", "Kein Problem."),
    ("ลาก่อน", "la kon", "Phrase", "auf Wiedersehen", "Begruessung & Hoeflichkeit",
     "ลาก่อน แล้วพบกันใหม่", "Auf Wiedersehen, bis bald."),
    ("แล้วเจอกัน", "laeo choe kan", "Phrase", "bis spaeter", "Begruessung & Hoeflichkeit",
     "แล้วเจอกันพรุ่งนี้", "Bis morgen."),
    ("โชคดี", "chok di", "Phrase", "viel Glueck", "Begruessung & Hoeflichkeit",
     "โชคดีนะ", "Viel Glueck!"),
    ("ยินดีที่ได้รู้จัก", "yindi thi dai ruchak", "Phrase", "freut mich, dich kennenzulernen",
     "Begruessung & Hoeflichkeit",
     "ยินดีที่ได้รู้จักครับ", "Freut mich, Sie kennenzulernen."),
    ("เชิญ", "choen", "Verb", "bitte sehr; treten Sie ein", "Begruessung & Hoeflichkeit",
     "เชิญนั่งครับ", "Nehmen Sie bitte Platz."),
    ("ขอ", "kho", "Verb", "bitten um; erbitten", "Begruessung & Hoeflichkeit",
     "ขอน้ำหน่อยครับ", "Etwas Wasser, bitte."),

    # --- Gefuehle ---
    ("เกลียด", "kliat", "Verb", "hassen", "Gefuehle & Kommunikation",
     "ฉันเกลียดอากาศร้อน", "Ich hasse heisses Wetter."),
    ("ดีใจ", "di chai", "Verb", "sich freuen", "Gefuehle & Kommunikation",
     "ฉันดีใจที่ได้เจอคุณ", "Ich freue mich, dich zu sehen."),
    ("เสียใจ", "sia chai", "Verb", "traurig sein", "Gefuehle & Kommunikation",
     "เขาเสียใจมากเมื่อได้ยินข่าว", "Er war sehr traurig, als er die Nachricht hoerte."),
]
